version: "3.8"

services:
  backend-dev:
    image: backend-dev
    container_name: backend-dev
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    working_dir: /usr/src/app/backend
    volumes:
      - ./backend:/usr/src/app/backend:cached
      - /usr/src/app/backend/node_modules
  frontend-dev:
    image: frontend-dev
    container_name: frontend-dev
    build:
      context: client
      dockerfile: ./Dockerfile.dev
    ports:
      - 3000:3000
    working_dir: /usr/src/app/client
    volumes:
      - ./client:/usr/src/app/client:cached
      - /usr/src/app/client/node_modules
