version: "3.8"

services:
  backend-dev:
    image: backend-dev
    container_name: backend-dev
    build:
      context: backend
      dockerfile: ./Dockerfile.dev
    environment:
      NODE_ENV: development
    ports:
      - 5000:5000
    working_dir: /usr/src/app/backend
    volumes:
      - ./backend:/usr/src/app/backend:cached
      - /usr/src/app/backend/node_modules
