version: "3.8"

services:
  backend:
    image: backend
    container_name: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
    working_dir: /usr/src/app/backend
    restart: always
  client:
    image: client
    container_name: client
    build:
      context: client
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
    ports:
      - 3000:3000
    restart: always
