FROM node:14-alpine
ENV APP_ID=backend
ENV PORT=5000
ENV LOG_LEVEL=debug
ENV REQUEST_LIMIT=100kb
ENV SESSION_SECRET=mySecret

#Swagger
ENV SWAGGER_API_SPEC=/api/spec

RUN mkdir -p /usr/src/app/backend
WORKDIR /usr/src/app/backend
COPY ["package.json", "yarn.lock", "./"]
RUN apk add yarn
RUN yarn install --silent && npm i -g nodemon pino-pretty && mv node_modules ../
COPY . .
EXPOSE 5000
CMD ["yarn", "dev"]
