# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: lambda-func

frameworkVersion: "2"

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x

# The `functions` block defines what code to deploy
functions:
  helloWorld:
    handler: handler.helloWorld
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: hello-world
          method: get
          cors: true
<<<<<<< HEAD
  
=======

>>>>>>> f7119a49f6fd461c60d404ab008b674da131cd50
  shareTodo:
    handler: handler.shareTodo
    events:
      - http:
          path: share-todo
          method: post
          cors: true
