# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  slack: circleci/slack@4.2.0

aliases:
  - &restore-yarn-cache
    name: Restore yarnpkg cache
    keys:
      - yarn-packages-{{ checksum "yarn.lock" }}
      - yarn-packages-

  - &save-yarn-cache
    name: Save yarnpkg cache
    paths:
      - ~/.cache/yarn
    key: yarn-packages-{{ checksum "yarn.lock" }}

  - &install-yarn sudo npm install --global --force yarn@1.22.4

  - &filter-master-only
    branches:
      only:
        - master

  - &slack-success-notification
    event: pass
    custom: |
      {
        "text": "",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "✅ *Success* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
            }
          },
          {
            "type": "sections",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "View job"
                },
                "url": "${CIRCLE_BUILD_URL}"
              }
            ]
          }
        ]
      }

  - &slack-fail-notification
    event: fail
    custom: |
      {
        "text": "",
        "blocks": [
          {
            "type": "section",
            "text": {
              "type": "mrkdwn",
              "text": "❌ *Failure* #${CIRCLE_BUILD_NUM} `${CIRCLE_PROJECT_REPONAME}` on `${CIRCLE_BRANCH}`"
            }
          },
          {
            "type": "actions",
            "elements": [
              {
                "type": "button",
                "text": {
                  "type": "plain_text",
                  "text": "View job"
                },
                "url": "${CIRCLE_BUILD_URL}"
              }
            ]
          }
        ]
      }

executors:
  default-executor:
    docker:
      - image: circleci/node:12.16.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
        environment:
          AWS-REGION: us-east-2

jobs:
  check-format:
    executor: default-executor
    steps:
      - checkout
      - run: *install-yarn
      - attach_workspace: { at: "." }
      - run: yarn prettier --check .

  checkout-code:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: yarn install --non-interactive --cache-folder ~/.cache/yarn
      - run:
          name: Check if yarn.lock changed during install
          command: git diff --exit-code yarn.lock
      - save_cache: *save-yarn-cache
      - persist_to_workspace:
          root: "."
          paths: [node_modules]

  build:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: *install-yarn
      - save_cache: *save-yarn-cache
      - attach_workspace: { at: "." }
      - run: yarn build
      - slack/notify: *slack-fail-notification
      - slack/notify: *slack-success-notification

  lint:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: *install-yarn
      - save_cache: *save-yarn-cache
      - attach_workspace: { at: "." }
      - run: yarn lint
      - slack/notify: *slack-fail-notification
      - slack/notify: *slack-success-notification

  run-app-tests:
    executor: default-executor
    steps:
      - checkout
      - restore_cache: *restore-yarn-cache
      - run: *install-yarn
      - save_cache: *save-yarn-cache
      - attach_workspace: { at: "." }
      - run: CI=true yarn test
      - slack/notify: *slack-fail-notification
      - slack/notify: *slack-success-notification

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  todo-app:
    # Run the welcome/run job in its own container
    jobs:
      - checkout-code
      - check-format:
          requires: [checkout-code]
      - build:
          requires: [check-format]
          context: slack-secrets
      - lint:
          requires: [check-format]
          context: slack-secrets
      - run-app-tests:
          requires: [build]
          context: slack-secrets
